import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { Prose } from "@/components/prose";
import { PostHeader } from "@/components/post-header";
import { getPost } from "@/lib/posts";

const SLUG = "why-small-posts-win";

export function generateMetadata(): Metadata {
  const post = getPost(SLUG);
  return { title: post?.title, description: post?.blurb };
}

export default function Page() {
  const post = getPost(SLUG);
  if (!post) notFound();

  return (
    <article>
      <PostHeader title={post.title} published={post.published} tags={post.tags} />
      <Prose>
        <p>
          This post exists to be copied. It is the shape every post in this repository takes: a
          directory under <code>app/posts/</code> holding exactly two files, a{" "}
          <code>meta.json</code> that the index reads and a <code>page.tsx</code> that renders the
          writing.
        </p>

        <h2>Nothing central to edit</h2>
        <p>
          Adding a post means adding a directory. There is no list of posts to append to, which
          means there is no file that two posts written at the same time both have to change. The
          index is generated by reading the filesystem at build time.
        </p>

        <h2>The writing is ordinary React</h2>
        <p>
          Body copy is JSX inside <code>&lt;Prose&gt;</code>, which applies the typography scope
          defined in <code>app/globals.css</code>. Because it is React, a post can hold anything a
          component can — a chart, a small interactive demo, a table — without a special pipeline
          for it. Keep interactive pieces in their own client component and leave the post itself
          a server component.
        </p>

        <h2>Delete this one</h2>
        <p>
          Once there is a real post, this example has done its job. Remove the directory; the index
          will stop listing it with no other change.
        </p>
      </Prose>
    </article>
  );
}
